authors:
  SamHollings:
    name: Sam Hollings        # Author name
    description: Principle Data Scientist # Author description
    avatar: https://avatars.githubusercontent.com/u/52575338?v=4         # Author avatar
    slug: SamHollings          # Author profile slug
    url: https://github.com/SamHollings            # Author website URL