authors:
  SamHollings:
    name: Sam Hollings        # Author name
    description: Head of Coding and Data Standards # Author description
    avatar: https://avatars.githubusercontent.com/u/52575338?v=4         # Author avatar
    slug: SamHollings          # Author profile slug
    url: https://github.com/SamHollings            # Author website URL

  AdamHollings:
    name: Adam Hollings        # Author name
    description: Principal Data Scientist # Author description
    avatar: https://avatars.githubusercontent.com/u/119732210?v=4         # Author avatar
    slug: AdamHollings          # Author profile slug
    url: https://github.com/AdamHollings            # Author website URL

  VickySmith:
    name: Vicky Smith        # Author name
    description: PhD Data Science Intern # Author description
    avatar: https://avatars.githubusercontent.com/u/72864814?v=4        # Author avatar
    slug: VickySmith          # Author profile slug
    url: https://v-smith.github.io/            # Author website URL

  willpoulett:
    name: Will Poulett        # Author name
    description: Senior Data Scientist # Author description
    avatar: https://avatars.githubusercontent.com/willpoulett      # Author avatar
    slug: WillPoulett          # Author profile slug
    url: https://github.com/willpoulett           # Author website URL

  AmaiaImazBlanco:
    name: Amaia Imaz Blanco    # Author name
    description: Senior Data Scientist # Author description
    avatar: https://avatars.githubusercontent.com/amaiaita      # Author avatar
    slug: AmaiaImazBlanco          # Author profile slug
    url: https://github.com/amaiaita           # Author website URL

  jpearson:
    name: Jonny Pearson    # Author name
    description: Lead Data Scientist # Author description
    avatar: https://avatars.githubusercontent.com/jrpearson-nhs      # Author avatar
    slug: JonnyPearson          # Author profile slug
    url: https://github.com/https://github.com/jrpearson-nhs         # Author website URL

  Michelle Nwachukwu:
    name: Michelle Nwachukwu    # Author name
    description: Graduate Data Scientist # Author description
    avatar: https://avatars.githubusercontent.com/u/52786160?v=4 # Author avatar
    slug: Michelle Nwachukwu          # Author profile slug
    url: https://github.com/michelle7707     # Author website URL

  Mia Noonan:
    name: Mia Noonan    # Author name
    description: Principal Data Scientist # Author description
    avatar: https://avatars.githubusercontent.com/amelianoonan1-nhs      # Author avatar
    slug: amelianoonan1-nhs          # Author profile slug
    url: https://github.com/amelianoonan1-nhs       # Author website URL
