authors:
  SamHollings:
    name: Sam Hollings        # Author name
    description: Principal Data Scientist # Author description
    avatar: https://avatars.githubusercontent.com/u/52575338?v=4         # Author avatar
    slug: SamHollings          # Author profile slug
    url: https://github.com/SamHollings            # Author website URL

  VickySmith:
    name: Vicky Smith        # Author name
    description: PhD Data Science Intern # Author description
    avatar: https://avatars.githubusercontent.com/u/72864814?v=4        # Author avatar
    slug: VickySmith          # Author profile slug
    url: https://v-smith.github.io/            # Author website URL

  willpoulett:
    name: Will Poulett        # Author name
    description: Senior Data Scientist # Author description
    avatar: https://avatars.githubusercontent.com/willpoulett      # Author avatar
    slug: WillPoulett          # Author profile slug
    url: https://github.com/willpoulett           # Author website URL

  AmaiaImazBlanco:
    name: Amaia Imaz Blanco    # Author name
    description: Senior Data Scientist # Author description
    avatar: https://avatars.githubusercontent.com/amaiaita      # Author avatar
    slug: AmaiaImazBlanco          # Author profile slug
    url: https://github.com/amaiaita           # Author website URL

  jpearson:
    name: Jonny Pearson    # Author name
    description: Lead Data Scientist # Author description
    avatar: https://avatars.githubusercontent.com/jrpearson-nhs      # Author avatar
    slug: JonnyPearson          # Author profile slug
    url: https://github.com/https://github.com/jrpearson-nhs         # Author website URL
